# Generated by Django 4.0.4 on 2022-06-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
