# Generated by Django 4.0.4 on 2022-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_notes_image_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, upload_to='note_image'),
        ),
    ]
